---
title: 'C&BS Co: scouring Twitter feedback'
author: "David Jackson"
date: "11/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(tidytext)
library(writexl)
```

## R Markdown


```{r}
rm(list=ls())
tweets <- readxl::read_excel("./Data/2019PreppingDataWk 9.xlsx")
```
```{r}
data(stop_words)
tweets_words <- tweets %>%
  unnest_tokens(word, Tweet) %>%
  anti_join(stop_words) %>% count(word, sort = TRUE)
```

### Bosse's Requirement
* Table of Key words matched to Tweet.

```{r}
keywords <- read_csv("keywords.csv")
tweets <- read_csv("tweets.csv", col_names = "tweet")

tweet_matched <- keywords %>% 
  mutate(tweet = map(word, 
                     ~ with(tweets, 
                            tweet[grepl(.x, tweet, ignore.case = TRUE)]))) %>% 
  unnest(tweet) 

head(tweet_matched,90)
```

#### More Cleaning

```{r}
df <- tweets_words
df$word <- ifelse(df$word =="bars","bar",df$word)
df$word <- ifelse(df$word =="bubbly","bubbles",df$word)
```


```{r}
df %>% top_n(5) %>% ggplot(aes	
(x=word,y=n)) + geom_col() +
  coord_flip()
```
```{r}
tweets_words %>% top_n(5) %>% ggplot(aes(x=reorder(word,n),y=n/sum(n))) + geom_col() +
  coord_flip()
```
```{r}
tweets_words %>% top_n(10) %>% ggplot(aes(x=reorder(word,n),y=n/sum(n))) + geom_col() +
  coord_flip()
```

### Word Cloud

```{r}
library(wordcloud)
df %>%
  anti_join(stop_words) %>%
  count(word) %>%
  with(wordcloud(word, n, max.words = 50))
```

```{r}
nrc_joy <- get_sentiments("nrc")
df %>%
  inner_join(nrc_joy) %>%
  count(word, sort = TRUE) %>% ggplot(aes(x=word,y=n)) +
  geom_col() + coord_flip()
```
```{r}
df %>%
  inner_join(get_sentiments("afinn")) %>%
  count(word, sort = TRUE) %>% ggplot(aes(x=word,y=n)) +
  geom_col() + coord_flip()
```

```{r}
df %>%
  inner_join(get_sentiments("nrc")) %>%
  count(word, sort = TRUE) %>% ggplot(aes(x=word,y=n)) +
  geom_col() + coord_flip()
```


