---
title: 'Preppin Data: Week 4(A)'
author: "David Jackson"
date: "10/25/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, error = FALSE,message = FALSE)
library(tidyverse)
library(scales)
library(lubridate)
library(readr)
library(readxl)
library(janitor)
library(flextable)

```

### Import Excel Workbook and Sheets

```{r}
rm(list=ls())
Manchester <- read_excel("./Data/PD2021Wk3Input.xlsx",sheet = "Manchester")
London <- read_excel("./Data/PD2021Wk3Input.xlsx",sheet = "London")
York <- read_excel("./Data/PD2021Wk3Input.xlsx",sheet = "York")
Leeds <- read_excel("./Data/PD2021Wk3Input.xlsx",sheet = "Leeds")
Birmingham <- read_excel("./Data/PD2021Wk3Input.xlsx",sheet = "Birmingham")
Target <- read_excel("./Data/PD2021Wk3Input.xlsx",sheet = "Target") 
```
```{r}
Week4 <- rbind(Manchester,London,York,Leeds,Birmingham)
Week4 <- janitor::clean_names(Week4)
```

```{r}
Week4$date <- lubridate::dmy(Week4$date)
Week4$quarter <- lubridate::quarter(Week4$date)
```

```{r}
sales_targets <- cbind(Week4,Target)
```

### Final Data Cleaning?

```{r}
sales_targets <- sales_targets %>% select(store:quarter,target)

sales_targets <- sales_targets %>% select(store,date,quarter,target,new_saddles:existing_bags)
```

## Pivot on Store,date,quarter,target

```{r}
sales_longer <- sales_targets %>% pivot_longer(cols=new_saddles:existing_bags,values_to = "Sales",names_to = "Product")
sales_longer$store <- as.factor(sales_longer$store)
sales_longer$Product <- as.factor(sales_longer$Product)
summary(sales_longer)
```

## Total Sales by Quarter and Store

```{r}
sales_summary <- sales_longer %>% group_by(quarter,store) %>%
  summarise(product_sold = sum(Sales))
           
```
```{r}
sales_Join <- left_join(sales_summary,Target)
```

```{r}
sales_Join$Diff <- sales_Join$product_sold - sales_Join$target
sales_Join$Diff1 <- sales_Join$target - sales_Join$product_sold
```
```{r}
quarter_sales <- sales_Join %>% arrange(quarter,desc(Diff)) 

```

### Shoutout to Dhiraj @ Slack.com R4DS Group

```{r}
quarter_sales %>% 
  dplyr::arrange(quarter, desc(Diff))%>% 
  dplyr::mutate(rank = 1:n()) %>%
  select(quarter,rank,store,product_sold,target,Diff)
```

###  Shoutout to Vikram @ Slack.com R4DS Group

```{r}
quarter_sales %>% 
  group_by(quarter) %>%
  mutate(Diff_rank = rank(desc(Diff))) %>%
  ungroup() %>%
  arrange(quarter, Diff_rank)
```

### Products Sold by Store and Quarter

```{r}
quarter_sales %>% ggplot(aes(x=store,y=product_sold)) +
  geom_col() + facet_wrap(~quarter)
```

```{r}
quarter_sales %>%  ggplot(aes(x=reorder(quarter,product_sold),y=product_sold)) +
  geom_col() + facet_wrap(~store)
```

```{r}
quarter_sales %>%  ggplot(aes(x=reorder(quarter,Diff1),y=Diff1)) +
  geom_col() + facet_wrap(~store) 
```

### Products Sold by Quarter

```{r}
sales_longer %>% group_by(Product,quarter) %>%
  summarise(qty_sold = sum(Sales)) %>%
  ggplot(aes(x=Product,qty_sold,fill=quarter,group= quarter)) +
  geom_col() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```
```{r}
sales_longer %>% group_by(Product,quarter) %>%
  summarise(qty_sold = sum(Sales)) %>%
  ggplot(aes(x=quarter,qty_sold,fill=Product,group= Product)) +
  geom_col() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```

```{r}
sales_longer %>% group_by(Product,quarter) %>%
  summarise(qty_sold = sum(Sales)) %>%
  ggplot(aes(x=quarter,qty_sold)) +
  geom_col() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1)) + facet_wrap(~Product)
```

### Total Quantity Sold by Day

```{r}
sales_longer %>% group_by(date) %>%
  summarise(total_quantity = sum(Sales)) %>%
  ggplot(aes(x=date,y=total_quantity)) + geom_line() + 
  labs(title = "Total Quantity by Date")
```

### Total Products Sold by Day

```{r}
sales_longer %>% group_by(Product,date) %>%
  summarise(total_quantity = sum(Sales,na.rm =T)) %>%
  ggplot(aes(x=date,y=total_quantity)) + geom_line() + 
  labs(title = "Total Products by Date") + facet_wrap(~Product) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```

### Total Sales by Store

```{r}
sales_longer %>% group_by(store,date) %>%
  summarise(total_quantity = sum(Sales,na.rm =T)) %>%
  ggplot(aes(x=date,y=total_quantity,fill=store)) + geom_area()
```


```{r}
sales_longer %>% group_by(store,date) %>%
  summarise(total_quantity = sum(Sales,na.rm =T)) %>%
  ggplot(aes(x=date,y=total_quantity,fill=store)) + geom_area(show.legend = FALSE) +   facet_wrap(~store) + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
```
